#COS:
#  secretId: AKIDpkSwKXX7UfeT4TgiZDamPp35uZMDuOfh
#  secretKey: vd7xb4MhpiOr9E9vYyBIHE0b3JMCrKZa
#  bucket: xxll-1316295555
#  region: ap-chengdu
#  url: https://xxll-1316295555.cos.ap-chengdu.myqcloud.com
